/**
 * Represents the current connection state of the Gemini Live session.
 */
export enum StreamStatus {
  DISCONNECTED = 'DISCONNECTED',
  CONNECTING = 'CONNECTING',
  CONNECTED = 'CONNECTED',
  ERROR = 'ERROR',
}

/**
 * Represents a single segment of the transcript conversation.
 * Can be a user input or a model response.
 */
export interface TranscriptSegment {
  id: string;
  sender: 'user' | 'model';
  text: string;
  timestamp: Date;
  /** Indicates if the segment is currently being streamed/generated */
  isPartial: boolean;
}

/**
 * Structured output generated by the Note Organizer service.
 */
export interface OrganizedNote {
  title: string;
  summary: string;
  topics: string[];
  actionItems: string[];
  decisions: string[];
  sentiment: 'positive' | 'neutral' | 'negative';
  timestamp: string;
}

/**
 * Raw frequency data for the audio visualizer.
 */
export interface AudioVisualizerData {
  values: number[];
}

/**
 * Data point for the topic frequency chart.
 */
export interface StatPoint {
  topic: string;
  count: number;
}

/**
 * User-configurable settings for the audio pipeline.
 */
export interface AudioConfig {
  /** 
   * 'interactive': Low latency, best for real-time conversation.
   * 'balanced': Higher buffer, better audio quality.
   * 'playback': Maximum buffer, best for listening (not used for mic input).
   */
  latencyMode: 'interactive' | 'balanced' | 'playback';
  /** 
   * RMS threshold (0.0 - 0.05). Audio below this level is silenced.
   * Helps prevent background noise from triggering the model.
   */
  noiseGateThreshold: number; 
}